import { GeometryParameter } from "../../parameter/parameter";
export class Cube {
  static cube(size: number, color: number[]) {
    const verticesData = [
      -size,
      -size,
      size,
      size,
      -size,
      size,
      size,
      size,
      size,
      -size,
      size,
      size,
      -size,
      -size,
      -size,
      -size,
      size,
      -size,
      size,
      size,
      -size,
      size,
      -size,
      -size,
      -size,
      size,
      -size,
      -size,
      size,
      size,
      size,
      size,
      size,
      size,
      size,
      -size,
      -size,
      -size,
      -size,
      size,
      -size,
      -size,
      size,
      -size,
      size,
      -size,
      -size,
      size,
      size,
      -size,
      -size,
      size,
      size,
      -size,
      size,
      size,
      size,
      size,
      -size,
      size,
      -size,
      -size,
      -size,
      -size,
      -size,
      size,
      -size,
      size,
      size,
      -size,
      size,
      -size,
    ];

    const vertex = 1.0 / Math.sqrt(3.0);
    const normalData = [
      -vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      -vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      -vertex,
      -vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      -vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      -vertex,
    ];

    const colorMax = verticesData.length / 3.0;
    const colorData: number[] = [];

    [...Array(colorMax).keys()].forEach((_count) => {
      colorData.push(color[0], color[1], color[2], color[3]);
    });

    const textureCoordData = [
      0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0,
      1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0,
      0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
      1.0, 0.0, 1.0,
    ];

    const indicesData = [
      // front
      0, 1, 2, 0, 2, 3,
      // back
      4, 5, 6, 4, 6, 7,
      // top
      8, 9, 10, 8, 10, 11,
      // bottom
      12, 13, 14, 12, 14, 15,
      // right
      16, 17, 18, 16, 18, 19,
      // left
      20, 21, 22, 20, 22, 23,
    ];

    const data: GeometryParameter = {
      vertices: verticesData,
      normal: normalData,
      color: colorData,
      textureCoord: textureCoordData,
      indices: indicesData,
    };

    return data;
  }

  static cubeColor(size: number) {
    const verticesData = [
      -size,
      -size,
      size,
      size,
      -size,
      size,
      size,
      size,
      size,
      -size,
      size,
      size,
      -size,
      -size,
      -size,
      -size,
      size,
      -size,
      size,
      size,
      -size,
      size,
      -size,
      -size,
      -size,
      size,
      -size,
      -size,
      size,
      size,
      size,
      size,
      size,
      size,
      size,
      -size,
      -size,
      -size,
      -size,
      size,
      -size,
      -size,
      size,
      -size,
      size,
      -size,
      -size,
      size,
      size,
      -size,
      -size,
      size,
      size,
      -size,
      size,
      size,
      size,
      size,
      -size,
      size,
      -size,
      -size,
      -size,
      -size,
      -size,
      size,
      -size,
      size,
      size,
      -size,
      size,
      -size,
    ];

    const vertex = 1.0 / Math.sqrt(3.0);
    const normalData = [
      -vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      -vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      -vertex,
      -vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      -vertex,
      -vertex,
      -vertex,
      -vertex,
      -vertex,
      vertex,
      -vertex,
      vertex,
      vertex,
      -vertex,
      vertex,
      -vertex,
    ];

    const colorData: number[] = [
      1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0,
      1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0,
      1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0,
      1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0,
      0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0,
      1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0,
      1.0, 1.0, 0.0, 1.0, 1.0, 1.0,
    ];

    const textureCoordData = [
      0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0,
      1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0,
      0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
      1.0, 0.0, 1.0,
    ];

    const indicesData = [
      0, 1, 2, 0, 2, 3, 4, 5, 6, 4, 6, 7, 8, 9, 10, 8, 10, 11, 12, 13, 14, 12,
      14, 15, 16, 17, 18, 16, 18, 19, 20, 21, 22, 20, 22, 23,
    ];

    const data: GeometryParameter = {
      vertices: verticesData,
      normal: normalData,
      color: colorData,
      textureCoord: textureCoordData,
      indices: indicesData,
    };

    return data;
  }
}
